# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd1839b81922116f3a92be3f1c657f1f55436cb37132ad540b5f7864e8f82a37e8b1e6bdfc601ec76c56cfeb41433f35457d7f2da70cdbd9c26f1752bd404635

test:
  secret_key_base: fe7c7b8e74d7b4820dfebf60d242aaade4d28ac91175f570ad85942859a54b0e7955198ff4df0eaf828b2b1cf385dd762d698a572e4472f1d94cdbe5d918a4ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
