# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22dbda3275abf533127af95dbfcf396ee92c4e7b89ad7c1a18650d219e5b23aa5ba5fffe603049803c6cb5145a1b066be1a0776d9c19d8e6ddfde85010cf899b

test:
  secret_key_base: ba9188a369dbd4dbe5d66292ad0be31118565bb7272033de0ea6287e681b1a6f8f1fbdc633ef6d9d1af60e8c12707288272e8fceb2b8999417374c4637548829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
