# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d65e5892c9bd7ec4e4275798e9f1f2966a411841705732409654e2fa387002c4faa3d4faa8fec63cd7bfc12ae76145f606956d16b4c154b768ee51342a4a69

test:
  secret_key_base: 91ee726c91970ceadcc87ef2758148d9250251c3f8d7add42476ee804e3f33a524f420844914c94bb84e6728cf51c491aef0aa23cff05e28f3af6d57d7082926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
